on:
  pull_request:
    branches:
      - main
      - master
      - develop
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build:
    name: IOS Build & Release
    runs-on: macos-latest
    steps:
      - uses : actions/checkout@v1
      - uses : actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.0'
      - run: flutter pub get
      - run: flutter test
      - run: |
          cd ios
          rm podfile.lock
          pod deintegrate
          pod repo update
          pod install
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/ios/iphoneos/app.ipa"
          tag: ios.v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN}}
      